# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      debian_10_csv_file:  "/tmp/debian-10-syslog.csv"
      heroku_csv_file:  "/tmp/heroku-sample.csv"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest csvkit pandas tabulate
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --ignore F821

    - name: python-flake8
      uses: julianwachholz/flake8-action@v1.1.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: run-syslog-to-csv.py
      run: |
        python3 syslog-to-csv.py test-data/debian-10/syslog --csv-file ${debian_10_csv_file} 
    - name: run-kv-to-csv.py
      run: |
        python3 kv-to-csv.py test-data/heroku-log/sample --csv-file ${heroku_csv_file} 
    - name: head-csv-syslog
      run: |
        head ${debian_10_csv_file}
    - name: csvkit-report-syslog
      run: |
        csvstat  ${debian_10_csv_file}
    - name: head-csv-kv
      run: |
        head ${heroku_csv_file}
    - name: csvkit-report-kv
      run: |
        csvstat  ${heroku_csv_file}
    - name: find-time-gaps
      run: |
        python3 find-time-gaps.py -f ${debian_10_csv_file}  real_date -g 120 --output-format=markdown









